import StyledComponentsRegistry from 'src/lib/registry.jsx';

// eslint-disable-next-line camelcase
import { Fira_Code, Noto_Sans_KR } from 'next/font/google';

const fc = Fira_Code({
  subsets: ['latin'],
  variable: '--font-fira-code',
  display: 'swap',
});

const bg = Noto_Sans_KR({
  subsets: ['latin'],
  variable: '--font-noto-sans-kr',
  display: 'swap',
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const RootLayout = ({ children }) => {
  return (
    <html lang="kr" className={`${fc.variable} ${bg.variable}`}>
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
